---
- hosts: all
  gather_facts: yes
  vars:
    rocommunity: IB_RO

  tasks:
   - name: Install webtatic repo
     yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

   - name: Install necessary packages
     yum: state=present name={{ item }}
     with_items:
          - php70w
          - php70w-cli
          - php70w-gd
          - php70w-mysql
          - php70w-snmp 
          - php70w-pear
          - php70w-curl
          - php70w-common 
          - httpd 
          - net-snmp 
          - mariadb
          - ImageMagick 
          - jwhois
          - nmap 
          - mtr 
          - rrdtool
          - MySQL-python
          - net-snmp-utils
          - cronie 
          - php70w-mcrypt
          - fping
          - git
          - mariadb-server
          - mariadb
          - php70w-ldap

   - pear: name=Net_IPv4-1.3.4 name=Net_IPv6-1.2.2b2 state=present

   - name: Add group
     group: name=librenms state=present

   - name: Configure SNMP
     shell: echo rocommunity {{ rocommunity }} > /etc/snmp/snmpd.conf

   - git: repo=git://github.com/librenms/librenms.git dest=/opt/librenms

   - get_url: url=https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro dest=/usr/bin/distro

   - name: Add user
     user: name=librenms system=yes home=/opt/librenms append=yes groups=librenms,apache

   - name: Create necessary directories
     file: path=/opt/librenms/rrd state=directory mode=0775 owner=librenms group=librenms
     file: path=/opt/librenms/logs state=directory mode=0775

   - name: Get distro definitions
     file: path=/usr/bin/distro mode="a+rwx"

   - name: Setup cronjob
     raw: cp /opt/librenms/librenms.nonroot.cron /etc/cron.d/librenms

   - name: Remove Apache welcome file
     raw: rm -f rm -f /etc/httpd/conf.d/welcome.conf

   - name: Restart Apache
     service: name=httpd state=restarted enabled=yes

   - name: Restart SNMP
     service: name=snmpd state=restarted enabled=yes

   - name: Restart MariaDB
     service: name=mariadb state=restarted enabled=yes

